### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by davidorel** [ottensa/severus-snake#3]
Hello  , i ma tryong this component , followed the steps to install an d i have this messag e

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.talend.sdk.component.runtime.manager.asm.Unsafes (file:/C:/Talend_BD/TOS_BD-20211109_1610-V8.0.1/configuration/.m2/repository/org/talend/sdk/component/component-runtime-manager/1.37.0/component-runtime-manager-1.37.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of org.talend.sdk.component.runtime.manager.asm.Unsafes
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.NoClassDefFoundError: routines/system/Dynamic
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2473)
	at org.talend.sdk.component.runtime.record.RecordConverters$MappingMeta.newRecord(RecordConverters.java:500)
	at org.talend.sdk.component.runtime.di.InputsHandler.lambda$asInputFactory$2(InputsHandler.java:51)
	at org.talend.sdk.component.runtime.output.ProcessorImpl.lambda$buildProcessParamBuilder$5(ProcessorImpl.java:167)
	at org.talend.sdk.component.runtime.output.ProcessorImpl.lambda$onNext$10(ProcessorImpl.java:264)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at org.talend.sdk.component.runtime.output.ProcessorImpl.onNext(ProcessorImpl.java:265)
	at org.talend.sdk.component.runtime.manager.chain.AutoChunkProcessor.onElement(AutoChunkProcessor.java:39)
	at jobs_rman_sync.testgdrve_0_1.testGDrve.tFixedFlowInput_1Process(testGDrve.java:864)
	at jobs_rman_sync.testgdrve_0_1.testGDrve.runJobInTOS(testGDrve.java:1419)
	at jobs_rman_sync.testgdrve_0_1.testGDrve.main(testGDrve.java:1257)
Caused by: java.lang.ClassNotFoundException: routines.system.Dynamic
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 19 more`

**Comment by bgunics-talend** [comment]
Hello @davidorel 
I'm not sure about your studio version but based on the error it looks it has: component-runtime-manager/1.37.0
I think we'd have to bump the component-runtime version(s) as this project is based on the 1.1.25: https://github.com/ottensa/severus-snake/blob/main/pom.xml#L41 
And these should be more or less matched: https://talend.github.io/component-runtime/main/latest/compatibility.html#_compatibility_matrix

**Comment by davidorel** [comment]
Hello
My studio version is 8.0.1  2021/11/09

it's Talend Open Studio for Big Data

**Comment by bgunics-talend** [comment]
I recompiled it using 1.52 (which corresponds with the version I have in my studio) and I was able to load it.
I suggest to checkout and compile yourself using 1.37.0 which should make it aligned with your studio version.

**Comment by davidorel** [comment]
Hi 
I've tested your solution and it's the same 

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.talend.sdk.component.runtime.manager.asm.Unsafes (file:/C:/Talend_BD/TOS_BD-20211109_1610-V8.0.1/configuration/.m2/repository/org/talend/sdk/component/component-runtime-manager/1.37.0/component-runtime-manager-1.37.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of org.talend.sdk.component.runtime.manager.asm.Unsafes
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.NoClassDefFoundError: routines/system/Dynamic
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2473)
	at org.talend.sdk.component.runtime.record.RecordConverters$MappingMeta.newRecord(RecordConverters.java:500)
	at org.talend.sdk.component.runtime.di.InputsHandler.lambda$asInputFactory$2(InputsHandler.java:51)
	at org.talend.sdk.component.runtime.output.ProcessorImpl.lambda$buildProcessParamBuilder$5(ProcessorImpl.java:167)
	at org.talend.sdk.component.runtime.output.ProcessorImpl.lambda$onNext$10(ProcessorImpl.java:264)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at org.talend.sdk.component.runtime.output.ProcessorImpl.onNext(ProcessorImpl.java:265)
	at org.talend.sdk.component.runtime.manager.chain.AutoChunkProcessor.onElement(AutoChunkProcessor.java:39)
	at jobs_rman_sync.testgdrve_0_1.testGDrve.tFixedFlowInput_1Process(testGDrve.java:864)
	at jobs_rman_sync.testgdrve_0_1.testGDrve.runJobInTOS(testGDrve.java:1419)
	at jobs_rman_sync.testgdrve_0_1.testGDrve.main(testGDrve.java:1257)
Caused by: java.lang.ClassNotFoundException: routines.system.Dynamic
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 19 more`
Compilation logs 

`[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< de.ottensa:severus-snake >----------------------
[INFO] Building A Component Family 0.0.1
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/talend/sdk/component/component-api/1.52.0/component-api-1.52.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/talend/sdk/component/component-api/1.52.0/component-api-1.52.0.pom (3.0 kB at 11 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/talend/sdk/component/component-runtime/1.52.0/component-runtime-1.52.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/talend/sdk/component/component-runtime/1.52.0/component-runtime-1.52.0.pom (67 kB at 688 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/talend/sdk/component/component-bom/1.52.0/component-bom-1.52.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/talend/sdk/component/component-bom/1.52.0/component-bom-1.52.0.pom (10 kB at 181 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/talend/sdk/component/component-api/1.52.0/component-api-1.52.0.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/talend/sdk/component/component-api/1.52.0/component-api-1.52.0.jar (160 kB at 1.1 MB/s)
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ severus-snake ---
[INFO] Deleting C:\Users\david\Documents\MesDevs\severus python\severus-snake\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ severus-snake ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ severus-snake ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to C:\Users\david\Documents\MesDevs\severus python\severus-snake\target\classes
[INFO]
[INFO] --- talend-component-maven-plugin:1.1.25:svg2png (talend-svg2png) @ severus-snake ---
[INFO]
[INFO] --- talend-component-maven-plugin:1.1.25:validate (talend-validate) @ severus-snake ---
[WARNING] You don't validate placeholders are set, maybe think about setting validatePlaceholder=true
[WARNING] You don't validate wording rules, maybe think about setting validateWording=true
[ERROR] No 'icons/Python.svg' found, this will run in degraded mode in Talend Cloud
[ERROR] No 'icons/Script.svg' found, this will run in degraded mode in Talend Cloud
[INFO] Component should declare a custom Exception that inherits from ComponentException.
[INFO] Validated components: ScriptProcessor
[INFO]
[INFO] --- talend-component-maven-plugin:1.1.25:dependencies (talend-dependencies) @ severus-snake ---
[INFO] Generated C:\Users\david\Documents\MesDevs\severus python\severus-snake\target\classes\TALEND-INF\dependencies.txt
[INFO]
[INFO] --- talend-component-maven-plugin:1.1.25:scan-descriptor (talend-scan-descriptor) @ severus-snake ---
[INFO]
[INFO] --- talend-component-maven-plugin:1.1.25:asciidoc (talend-asciidoc) @ severus-snake ---
[INFO] Generated C:\Users\david\Documents\MesDevs\severus python\severus-snake\target\classes\TALEND-INF\documentation.adoc
[INFO] Attaching C:\Users\david\Documents\MesDevs\severus python\severus-snake\target\classes\TALEND-INF\documentation.adoc
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ severus-snake ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\david\Documents\MesDevs\severus python\severus-snake\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ severus-snake ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M4:test (default-test) @ severus-snake ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ severus-snake ---
[INFO] Building jar: C:\Users\david\Documents\MesDevs\severus python\severus-snake\target\severus-snake-0.0.1.jar
[INFO]
[INFO] --- talend-component-maven-plugin:1.1.25:car (talend-car) @ severus-snake ---
[INFO] Created C:\Users\david\Documents\MesDevs\severus python\severus-snake\target\severus-snake-0.0.1.car
[INFO] Attached C:\Users\david\Documents\MesDevs\severus python\severus-snake\target\severus-snake-0.0.1.car with classifier component
[INFO]
[INFO] --- talend-component-maven-plugin:1.1.25:deploy-in-studio (default-cli) @ severus-snake ---
[INFO] Installing development version of de.ottensa:severus-snake:0.0.1 in C:\Talend_BD\TOS_BD-20211109_1610-V8.0.1
[INFO] black.ninia:jep:jar:3.9.0:compile already exists, skipping
[INFO] Installed de.ottensa:severus-snake:0.0.1 at C:\Talend_BD\TOS_BD-20211109_1610-V8.0.1\configuration\.m2\repository\de\ottensa\severus-snake\0.0.1\severus-snake-0.0.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.052 s
[INFO] Finished at: 2022-12-29T14:07:43+01:00
[INFO] ------------------------------------------------------------------------`

The job 

![image](https://user-images.githubusercontent.com/112712285/209955657-81059f4a-8f50-493c-bb77-f54c159fca40.png)

**Comment by bgunics-talend** [comment]
Please subscribe / follow this issue in JIRA: https://jira.talendforge.org/browse/TDI-45180

**Comment by davidorel** [comment]
What is the link with my problem ?

**Comment by bgunics-talend** [comment]
Hello @davidorel ,

Could you try to build this component using 1.53 version of runtime?
https://talend.github.io/component-runtime/main/latest/changelog.html#_version_1_53_0 
It contains the fix for TOS.

**Comment by davidorel** [comment]
Hello 
I don't know how i can make that , is it possible for you to make a version with this fix ? 

Thx

**Comment by davidorel** [comment]
After trying to buil with 1.53 and 1.37 , here are the logs 
~~~
Démarrage du Job testGDrve à 14:00 26/06/2023.
[statistics] connecting to socket on port 3709
[statistics] connected
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.talend.sdk.component.runtime.manager.asm.Unsafes (file:/C:/Talend_BD/TOS_BD-20211109_1610-V8.0.1/configuration/.m2/repository/org/talend/sdk/component/component-runtime-manager/1.37.0/component-runtime-manager-1.37.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of org.talend.sdk.component.runtime.manager.asm.Unsafes
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.NoClassDefFoundError: routines/system/Dynamic
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2473)
	at org.talend.sdk.component.runtime.record.RecordConverters$MappingMeta.newRecord(RecordConverters.java:500)
	at org.talend.sdk.component.runtime.di.InputsHandler.lambda$asInputFactory$2(InputsHandler.java:51)
	at org.talend.sdk.component.runtime.output.ProcessorImpl.lambda$buildProcessParamBuilder$5(ProcessorImpl.java:167)
	at org.talend.sdk.component.runtime.output.ProcessorImpl.lambda$onNext$10(ProcessorImpl.java:264)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at org.talend.sdk.component.runtime.output.ProcessorImpl.onNext(ProcessorImpl.java:265)
	at org.talend.sdk.component.runtime.manager.chain.AutoChunkProcessor.onElement(AutoChunkProcessor.java:39)
	at jobs_rman_sync.testgdrve_0_1.testGDrve.tFixedFlowInput_1Process(testGDrve.java:864)
	at jobs_rman_sync.testgdrve_0_1.testGDrve.runJobInTOS(testGDrve.java:1419)
	at jobs_rman_sync.testgdrve_0_1.testGDrve.main(testGDrve.java:1257)
Caused by: java.lang.ClassNotFoundException: routines.system.Dynamic
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 19 more
[statistics] disconnected
~~~
